
package GUI;

import Logic.LogicController;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * @author kuan
 */
public class AddEvent extends javax.swing.JDialog {

    /** Creates new form AddExpense */
    public AddEvent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addKeyListener(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        AddExpenseBackground = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        AddEventButton = new javax.swing.JButton();
        TitleText = new javax.swing.JTextField();
        DescriptionTextBackground = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        AddExpenseBackground.setBackground(new java.awt.Color(227, 227, 227));
        AddExpenseBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TitleLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        TitleLabel.setText("Title:");

        DescriptionLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        DescriptionLabel.setText("Description:");

        AddEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); // NOI18N
        AddEventButton.setBorderPainted(false);
        AddEventButton.setContentAreaFilled(false);
        AddEventButton.setFocusPainted(false);
        AddEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddEventButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddEventButtonMousePressed(evt);
            }
        });
        AddEventButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AddEventButtonMouseMoved(evt);
            }
        });
        AddEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventButtonActionPerformed(evt);
            }
        });

        TitleText.setFont(new java.awt.Font("Ubuntu", 0, 14));
        TitleText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        TitleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TitleTextFocusGained(evt);
            }
        });
        TitleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitleTextKeyTyped(evt);
            }
        });

        DescriptionTextBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        DescriptionTextArea.setLineWrap(true);
        DescriptionTextArea.setRows(1);
        DescriptionTextArea.setWrapStyleWord(true);
        DescriptionTextBackground.setViewportView(DescriptionTextArea);
        DescriptionTextArea.setBorder(BorderFactory.createCompoundBorder(
            DescriptionTextArea.getBorder(),
            BorderFactory.createEmptyBorder(0, 3, 0, 3)));

    javax.swing.GroupLayout AddExpenseBackgroundLayout = new javax.swing.GroupLayout(AddExpenseBackground);
    AddExpenseBackground.setLayout(AddExpenseBackgroundLayout);
    AddExpenseBackgroundLayout.setHorizontalGroup(
        AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
                    .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DescriptionLabel)
                        .addComponent(TitleLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DescriptionTextBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                .addComponent(AddEventButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    AddExpenseBackgroundLayout.setVerticalGroup(
        AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TitleLabel)
                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DescriptionLabel)
                .addComponent(DescriptionTextBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(AddEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    TitleText.setBorder(BorderFactory.createCompoundBorder(
        TitleText.getBorder(),
        BorderFactory.createEmptyBorder(0, 5, 0, 5)));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(AddExpenseBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(AddExpenseBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventButtonActionPerformed
        try {
            LogicController.addEvent(TitleText.getText(), DescriptionTextArea.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);  
            TitleText.grabFocus();
            return;
        }
        this.dispose();
    }//GEN-LAST:event_AddEventButtonActionPerformed

    private void AddEventButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventButtonMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        double dx = AddEventButton.getWidth()/2 - x;
        double dy = AddEventButton.getHeight()/2 - y;
        double sr = Math.sqrt(dx*dx + dy*dy );
        if (sr <= AddEventButton.getWidth()/2)
            AddEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonhover.png")));
        else
            AddEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));

    }//GEN-LAST:event_AddEventButtonMouseMoved

    private void AddEventButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventButtonMouseExited
        AddEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));
    }//GEN-LAST:event_AddEventButtonMouseExited

    private void TitleTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TitleTextFocusGained
        TitleText.setSelectionStart(0);
        TitleText.setSelectionEnd(TitleText.getText().length());
    }//GEN-LAST:event_TitleTextFocusGained

    private void TitleTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleTextKeyTyped
        if (evt.getKeyChar() == 10){
            try {
                LogicController.addEvent(TitleText.getText(), DescriptionTextArea.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);  
                TitleText.grabFocus();
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_TitleTextKeyTyped

    private void AddEventButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventButtonMousePressed
        AddEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonclick.png")));
    }//GEN-LAST:event_AddEventButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddEvent dialog = new AddEvent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventButton;
    private javax.swing.JPanel AddExpenseBackground;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JScrollPane DescriptionTextBackground;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleText;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
