
package GUI;

import Logic.Event.Event;
import Logic.LogicController;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * @author kuan
 */
public class EditEvent extends javax.swing.JDialog {

    /** Creates new form AddExpense */
    public EditEvent(java.awt.Frame parent, boolean modal, Event e) {
        super(parent, modal);
        initComponents();
        event = e;
        TitleText.setText(event.getTitle());
        DescriptionTextArea.setText(event.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddExpenseBackground = new javax.swing.JPanel();
        TitleText = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        EditEventButton = new javax.swing.JButton();
        DescriptionTextAreaBackground = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        AddExpenseBackground.setBackground(new java.awt.Color(227, 227, 227));
        AddExpenseBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TitleText.setFont(new java.awt.Font("Ubuntu", 0, 14));
        TitleText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        TitleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TitleTextFocusGained(evt);
            }
        });
        TitleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitleTextKeyTyped(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        TitleLabel.setText(" Title :");

        DescriptionLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        DescriptionLabel.setText("Description :");

        EditEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); // NOI18N
        EditEventButton.setBorderPainted(false);
        EditEventButton.setContentAreaFilled(false);
        EditEventButton.setFocusPainted(false);
        EditEventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditEventButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditEventButtonMousePressed(evt);
            }
        });
        EditEventButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EditEventButtonMouseMoved(evt);
            }
        });
        EditEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEventButtonActionPerformed(evt);
            }
        });

        DescriptionTextAreaBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        DescriptionTextArea.setLineWrap(true);
        DescriptionTextArea.setRows(1);
        DescriptionTextArea.setWrapStyleWord(true);
        DescriptionTextAreaBackground.setViewportView(DescriptionTextArea);
        DescriptionTextArea.setBorder(BorderFactory.createCompoundBorder(
            DescriptionTextArea.getBorder(),
            BorderFactory.createEmptyBorder(0, 3, 0, 3)));

    javax.swing.GroupLayout AddExpenseBackgroundLayout = new javax.swing.GroupLayout(AddExpenseBackground);
    AddExpenseBackground.setLayout(AddExpenseBackgroundLayout);
    AddExpenseBackgroundLayout.setHorizontalGroup(
        AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
                    .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DescriptionLabel)
                        .addComponent(TitleLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DescriptionTextAreaBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddExpenseBackgroundLayout.createSequentialGroup()
                    .addGap(0, 280, Short.MAX_VALUE)
                    .addComponent(EditEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    AddExpenseBackgroundLayout.setVerticalGroup(
        AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TitleLabel)
                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DescriptionLabel)
                .addComponent(DescriptionTextAreaBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(EditEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    TitleText.setBorder(BorderFactory.createCompoundBorder(
        TitleText.getBorder(),
        BorderFactory.createEmptyBorder(0, 5, 0, 5)));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(AddExpenseBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(AddExpenseBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEventButtonActionPerformed
        if (TitleText.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Oops, title needed...", "Title needed", JOptionPane.PLAIN_MESSAGE);  
            TitleText.grabFocus();
            return;
        }
        try {
            LogicController.setEventTitle(event,TitleText.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);  
            TitleText.grabFocus();
            return;
        }
        LogicController.setEventDescription(event, DescriptionTextArea.getText());
        this.dispose();
    }//GEN-LAST:event_EditEventButtonActionPerformed

    private void EditEventButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEventButtonMouseExited
        EditEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));
    }//GEN-LAST:event_EditEventButtonMouseExited

    private void EditEventButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEventButtonMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        double dx = EditEventButton.getWidth()/2 - x;
        double dy = EditEventButton.getHeight()/2 - y;
        double sr = Math.sqrt(dx*dx + dy*dy );
        if (sr <= EditEventButton.getWidth()/2)
            EditEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonhover.png")));
        else
            EditEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));
    }//GEN-LAST:event_EditEventButtonMouseMoved

    private void TitleTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TitleTextFocusGained
        TitleText.setSelectionStart(0);
        TitleText.setSelectionEnd(TitleText.getText().length());
    }//GEN-LAST:event_TitleTextFocusGained

    private void TitleTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleTextKeyTyped
        if (evt.getKeyChar() == 10){
            if (TitleText.getText().length() == 0){
                JOptionPane.showMessageDialog(this, "Oops, title needed...", "Title needed", JOptionPane.PLAIN_MESSAGE);  
                TitleText.grabFocus();
                return;
            }
            try {
                LogicController.setEventTitle(event,TitleText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);  
                TitleText.grabFocus();
                return;
            }
            LogicController.setEventDescription(event, DescriptionTextArea.getText());
            this.dispose();
        }
    }//GEN-LAST:event_TitleTextKeyTyped

    private void EditEventButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEventButtonMousePressed
        EditEventButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonclick.png")));
    }//GEN-LAST:event_EditEventButtonMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditEvent dialog = new EditEvent(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    Event event;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddExpenseBackground;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JScrollPane DescriptionTextAreaBackground;
    private javax.swing.JButton EditEventButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleText;
    // End of variables declaration//GEN-END:variables
}
