
package GUI;

import Logic.Budget.BudgetCategory;
import Logic.Budget.Expense;
import Logic.LogicController;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * @author kuan
 */
public class EditExpense extends javax.swing.JDialog {

    /** Creates new form AddExpense */
    public EditExpense(java.awt.Frame parent, boolean modal, Expense ex) {
        super(parent, modal);
        initComponents();
        exp = ex;
        bc = exp.getBudgetCategory().getEvent().getBudgetCategoryList();
        ubc = exp.getBudgetCategory().getEvent().getUncategorizedBudget();
        int at = 0;
        CategoryDropDown.addItem("None");
        for (int i = 0; i < bc.size(); i++){
            CategoryDropDown.addItem(bc.get(i).getName());
            if (bc.get(i) == ex.getBudgetCategory())
                at = i+1;
        }
        CategoryDropDown.setSelectedIndex(at);
        DescriptionText.setText(exp.getTitle());
        AmountText.setText((new BigDecimal(exp.getCost())).divide(new BigDecimal("100")).toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddExpenseBackground = new javax.swing.JPanel();
        CategoryDropDown = new javax.swing.JComboBox();
        CategoryLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        SubmitExpenseButton = new javax.swing.JButton();
        AmountText = new javax.swing.JTextField();
        DescriptionText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        AddExpenseBackground.setBackground(new java.awt.Color(227, 227, 227));
        AddExpenseBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        CategoryDropDown.setFont(new java.awt.Font("Ubuntu", 0, 14));
        CategoryDropDown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CategoryDropDown.setFocusable(false);

        CategoryLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        CategoryLabel.setText("Category :");

        DescriptionLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        DescriptionLabel.setText("Description :");

        AmountLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        AmountLabel.setText("Cost ($) :");

        SubmitExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); // NOI18N
        SubmitExpenseButton.setBorderPainted(false);
        SubmitExpenseButton.setContentAreaFilled(false);
        SubmitExpenseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubmitExpenseButton.setFocusPainted(false);
        SubmitExpenseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitExpenseButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitExpenseButtonMousePressed(evt);
            }
        });
        SubmitExpenseButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SubmitExpenseButtonMouseMoved(evt);
            }
        });
        SubmitExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitExpenseButtonActionPerformed(evt);
            }
        });

        AmountText.setFont(new java.awt.Font("Ubuntu", 0, 14));
        AmountText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        AmountText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AmountTextFocusGained(evt);
            }
        });
        AmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountTextKeyTyped(evt);
            }
        });

        DescriptionText.setFont(new java.awt.Font("Ubuntu", 0, 14));
        DescriptionText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        DescriptionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescriptionTextFocusGained(evt);
            }
        });
        DescriptionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DescriptionTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout AddExpenseBackgroundLayout = new javax.swing.GroupLayout(AddExpenseBackground);
        AddExpenseBackground.setLayout(AddExpenseBackgroundLayout);
        AddExpenseBackgroundLayout.setHorizontalGroup(
            AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
                        .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CategoryLabel)
                            .addComponent(DescriptionLabel)
                            .addComponent(AmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AmountText, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(CategoryDropDown, 0, 201, Short.MAX_VALUE)
                            .addComponent(DescriptionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddExpenseBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SubmitExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AddExpenseBackgroundLayout.setVerticalGroup(
            AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddExpenseBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddExpenseBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AmountText.setBorder(BorderFactory.createCompoundBorder(
            AmountText.getBorder(),
            BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    DescriptionText.setBorder(BorderFactory.createCompoundBorder(
        DescriptionText.getBorder(),
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(AddExpenseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(AddExpenseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitExpenseButtonActionPerformed
        BigDecimal amount = null;
        try {
            amount = new BigDecimal(AmountText.getText());
                   } catch (Exception expobj){
            JOptionPane.showMessageDialog(this, "Amount seems wrong..", "Oops", JOptionPane.PLAIN_MESSAGE);
            AmountText.setSelectionStart(0);
            AmountText.setSelectionEnd(AmountText.getText().length());
            return;
        }
        
        BudgetCategory b;
        if (CategoryDropDown.getSelectedIndex() > 0)
            b = bc.get(CategoryDropDown.getSelectedIndex()-1);
        else
            b = ubc;
        try {
            LogicController.setExpenseBudgetCategory(exp, b);
            LogicController.setExpenseTitle(exp,DescriptionText.getText());
            LogicController.setExpenseCost(exp,amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops", JOptionPane.PLAIN_MESSAGE);             
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_SubmitExpenseButtonActionPerformed

    private void SubmitExpenseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitExpenseButtonMouseExited
        SubmitExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); 
    }//GEN-LAST:event_SubmitExpenseButtonMouseExited

    private void SubmitExpenseButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitExpenseButtonMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        double dx = SubmitExpenseButton.getWidth()/2 - x;
        double dy = SubmitExpenseButton.getHeight()/2 - y;
        double sr = Math.sqrt(dx*dx + dy*dy );
        if (sr <= SubmitExpenseButton.getWidth()/2)
            SubmitExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonhover.png")));
        else
            SubmitExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));
    }//GEN-LAST:event_SubmitExpenseButtonMouseMoved

    private void AmountTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountTextKeyTyped
        if (evt.getKeyChar() == 10){
            BigDecimal amount = null;
            try {
                amount = new BigDecimal(AmountText.getText());
            } catch (Exception expobj){
                JOptionPane.showMessageDialog(this, "Amount seems wrong...", "Oops!", JOptionPane.PLAIN_MESSAGE);
                AmountText.setSelectionStart(0);
                AmountText.setSelectionEnd(AmountText.getText().length());
                return;
            }
            
            BudgetCategory b;
            if (CategoryDropDown.getSelectedIndex() > 0)
                b = bc.get(CategoryDropDown.getSelectedIndex()-1);
            else
                b = ubc;
            try {
                LogicController.setExpenseBudgetCategory(exp, b);
                LogicController.setExpenseTitle(exp,DescriptionText.getText());
                LogicController.setExpenseCost(exp,amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);
                return;
            }

            this.dispose();
        }
    }//GEN-LAST:event_AmountTextKeyTyped

    private void DescriptionTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescriptionTextFocusGained
        DescriptionText.setSelectionStart(0);
        DescriptionText.setSelectionEnd(DescriptionText.getText().length());
    }//GEN-LAST:event_DescriptionTextFocusGained

    private void AmountTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AmountTextFocusGained
        AmountText.setSelectionStart(0);
        AmountText.setSelectionEnd(AmountText.getText().length());
    }//GEN-LAST:event_AmountTextFocusGained

    private void DescriptionTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionTextKeyTyped
        if (evt.getKeyChar() == 10){
            BigDecimal amount = null;
            try {
                amount = new BigDecimal(AmountText.getText());
            } catch (Exception expobj){
                JOptionPane.showMessageDialog(this, "Amount seems wrong...", "Oops!", JOptionPane.PLAIN_MESSAGE);
                AmountText.setSelectionStart(0);
                AmountText.setSelectionEnd(AmountText.getText().length());
                return;
            }
            
            BudgetCategory b;
            if (CategoryDropDown.getSelectedIndex() > 0)
                b = bc.get(CategoryDropDown.getSelectedIndex()-1);
            else
                b = ubc;
            try {
                LogicController.setExpenseBudgetCategory(exp, b);
                LogicController.setExpenseTitle(exp,DescriptionText.getText());
                LogicController.setExpenseCost(exp,amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);
                return;
            }

            this.dispose();
        }
    }//GEN-LAST:event_DescriptionTextKeyTyped

    private void SubmitExpenseButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitExpenseButtonMousePressed
        SubmitExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonclick.png"))); 
    }//GEN-LAST:event_SubmitExpenseButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditExpense dialog = new EditExpense(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    ArrayList<BudgetCategory> bc;
    BudgetCategory ubc;
    Expense exp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddExpenseBackground;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountText;
    private javax.swing.JComboBox CategoryDropDown;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JButton SubmitExpenseButton;
    // End of variables declaration//GEN-END:variables
}
