
package GUI;

import Logic.Budget.BudgetCategory;
import Logic.LogicController;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * @author kuan
 */
public class EditBudgetCategory extends javax.swing.JDialog {

    /** Creates new form AddBudgetCategory */
    public EditBudgetCategory(java.awt.Frame parent, boolean modal,BudgetCategory budgetcat) {
        super(parent, modal);
        initComponents();
        bc = budgetcat;
        NameText.setText(bc.getName());
        AmountText.setText((new BigDecimal(bc.getAmount())).divide(new BigDecimal("100")).toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditBudgetCategoryBackground = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        SubmitBudgetCategoryButton = new javax.swing.JButton();
        AmountText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        EditBudgetCategoryBackground.setBackground(new java.awt.Color(227, 227, 227));
        EditBudgetCategoryBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        NameLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        NameLabel.setText("Name :");

        AmountLabel.setFont(new java.awt.Font("Ubuntu Bold", 0, 14));
        AmountLabel.setText("Amount ($):");

        SubmitBudgetCategoryButton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        SubmitBudgetCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); // NOI18N
        SubmitBudgetCategoryButton.setBorderPainted(false);
        SubmitBudgetCategoryButton.setContentAreaFilled(false);
        SubmitBudgetCategoryButton.setFocusPainted(false);
        SubmitBudgetCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitBudgetCategoryButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitBudgetCategoryButtonMousePressed(evt);
            }
        });
        SubmitBudgetCategoryButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SubmitBudgetCategoryButtonMouseMoved(evt);
            }
        });
        SubmitBudgetCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBudgetCategoryButtonActionPerformed(evt);
            }
        });

        AmountText.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        AmountText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        AmountText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AmountTextFocusGained(evt);
            }
        });
        AmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountTextKeyTyped(evt);
            }
        });

        NameText.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        NameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        NameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameTextFocusGained(evt);
            }
        });
        NameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout EditBudgetCategoryBackgroundLayout = new javax.swing.GroupLayout(EditBudgetCategoryBackground);
        EditBudgetCategoryBackground.setLayout(EditBudgetCategoryBackgroundLayout);
        EditBudgetCategoryBackgroundLayout.setHorizontalGroup(
            EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBudgetCategoryBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitBudgetCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditBudgetCategoryBackgroundLayout.createSequentialGroup()
                        .addGroup(EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameLabel)
                            .addComponent(AmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(AmountText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addContainerGap())
        );
        EditBudgetCategoryBackgroundLayout.setVerticalGroup(
            EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBudgetCategoryBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditBudgetCategoryBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitBudgetCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AmountText.setBorder(BorderFactory.createCompoundBorder(
            AmountText.getBorder(),
            BorderFactory.createEmptyBorder(0, 5, 0, 5)));
    NameText.setBorder(BorderFactory.createCompoundBorder(
        NameText.getBorder(),
        BorderFactory.createEmptyBorder(0, 5, 0, 5)));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(EditBudgetCategoryBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(EditBudgetCategoryBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBudgetCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBudgetCategoryButtonActionPerformed
        BigDecimal amount = null;
        try {
            amount = new BigDecimal(AmountText.getText());
        } catch (Exception exp){
            JOptionPane.showMessageDialog(this, "Oops, amount seems wrong...", "Amount error", JOptionPane.PLAIN_MESSAGE);
            AmountText.setSelectionStart(0);
            AmountText.setSelectionEnd(AmountText.getText().length());
            return;
        }
        
        try {
            LogicController.setBudgetCategoryName(bc, NameText.getText());
            LogicController.setBudgetCategoryAmount(bc, amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        this.dispose();
    }//GEN-LAST:event_SubmitBudgetCategoryButtonActionPerformed

    private void SubmitBudgetCategoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBudgetCategoryButtonMouseExited
        SubmitBudgetCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png"))); 
    }//GEN-LAST:event_SubmitBudgetCategoryButtonMouseExited

    private void SubmitBudgetCategoryButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBudgetCategoryButtonMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        double dx = SubmitBudgetCategoryButton.getWidth()/2 - x;
        double dy = SubmitBudgetCategoryButton.getHeight()/2 - y;
        double sr = Math.sqrt(dx*dx + dy*dy );
        if (sr <= SubmitBudgetCategoryButton.getWidth()/2)
            SubmitBudgetCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonhover.png")));
        else
            SubmitBudgetCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbutton.png")));
    }//GEN-LAST:event_SubmitBudgetCategoryButtonMouseMoved

    private void AmountTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountTextKeyTyped
        if (evt.getKeyChar() == 10){
            BigDecimal amount = null;
            try {
                amount = new BigDecimal(AmountText.getText());
            } catch (Exception exp){
                JOptionPane.showMessageDialog(this, "Oops, amount seems wrong...", "Amount error", JOptionPane.PLAIN_MESSAGE);
                AmountText.setSelectionStart(0);
                AmountText.setSelectionEnd(AmountText.getText().length());
                return;
            }
            
            try {
                LogicController.setBudgetCategoryName(bc, NameText.getText());
                LogicController.setBudgetCategoryAmount(bc, amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
            } catch (Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_AmountTextKeyTyped

    private void AmountTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AmountTextFocusGained
        AmountText.setSelectionStart(0);
        AmountText.setSelectionEnd(AmountText.getText().length());
    }//GEN-LAST:event_AmountTextFocusGained

    private void NameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTextFocusGained
        NameText.setSelectionStart(0);
        NameText.setSelectionEnd(NameText.getText().length());
    }//GEN-LAST:event_NameTextFocusGained

    private void NameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextKeyTyped
        if (evt.getKeyChar() == 10){
        
            BigDecimal amount = null;
            try {
                amount = new BigDecimal(AmountText.getText());
            } catch (Exception exp){
                JOptionPane.showMessageDialog(this, "Amount seems wrong..", "Oops!", JOptionPane.PLAIN_MESSAGE);
                AmountText.setSelectionStart(0);
                AmountText.setSelectionEnd(AmountText.getText().length());
                return;
            }
            try {
                LogicController.setBudgetCategoryName(bc, NameText.getText());
                LogicController.setBudgetCategoryAmount(bc, amount.multiply(new BigDecimal(""+100)).toBigInteger().longValue());
            } catch (Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage()+"..", "Oops!", JOptionPane.PLAIN_MESSAGE);
                return;
            }

            this.dispose();
        }
    }//GEN-LAST:event_NameTextKeyTyped

    private void SubmitBudgetCategoryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBudgetCategoryButtonMousePressed
            SubmitBudgetCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submitbuttonclick.png")));
    }//GEN-LAST:event_SubmitBudgetCategoryButtonMousePressed

    BudgetCategory bc;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBudgetCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBudgetCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBudgetCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBudgetCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditBudgetCategory dialog = new EditBudgetCategory(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountText;
    private javax.swing.JPanel EditBudgetCategoryBackground;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JButton SubmitBudgetCategoryButton;
    // End of variables declaration//GEN-END:variables
}
